image:
  tag: v0.6.3

extraArgs:
  kubelet-insecure-tls: true
  kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
  kubelet-use-node-status-port: true
  metric-resolution: 15s

livenessProbe:
  initialDelaySeconds: 30
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 30
  failureThreshold: 6
