apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
data:
  SECRET_KEY: "django-app"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "project"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "postgres"  
  POSTGRES_PORT: "5432"